/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    jobs: Job;
    media: Media;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    company: Company;
  };
  locale: 'en' | 'it';
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    badges?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            appearance?: 'badge' | null;
          };
          id?: string | null;
        }[]
      | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    backgroundImage?: (string | null) | Media;
  };
  layout?:
    | (
        | TextBlock
        | CtaBlock
        | MilestonesBlock
        | ClientsBlock
        | FeaturesBlock
        | AwardsBlock
        | StatsBlock
        | GridBlock
        | BentoBlock
        | TestimonialsBlock
        | FAQBlock
        | TeamBlock
        | RelatedPostsBlock
        | FormBlock
        | BrandBlock
        | JobsBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug?: string | null;
  slugLock?: boolean | null;
  publishedAt?: string | null;
  editedAt?: string | null;
  thumbnail?: (string | null) | Media;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
        avatar?: (string | null) | Media;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  color?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: (string | null) | Media;
  role?: string | null;
  policies: ('postsEditor' | 'postsContributor' | 'webDesigner' | 'administrator')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  media?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MilestonesBlock".
 */
export interface MilestonesBlock {
  title?: string | null;
  type: 'timeline' | 'roadmap';
  milestones: {
    title: string;
    date: string;
    status: 'completed' | 'active' | 'upcoming';
    text?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    media?: (string | null) | Media;
    id?: string | null;
  }[];
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'milestones';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientsBlock".
 */
export interface ClientsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  clients: {
    logo: string | Media;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'clients';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  features: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    icon?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardsBlock".
 */
export interface AwardsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  awards: {
    issuer: string;
    name: string;
    logo: string | Media;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'awards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  stats?:
    | {
        label: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlock".
 */
export interface GridBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  size?: ('default' | 'large') | null;
  rows?:
    | {
        items?:
          | {
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              background: {
                type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
                inverted?: boolean | null;
                dark?: boolean | null;
                backgroundImage?: (string | null) | Media;
                color?: string | null;
                colorStops?:
                  | {
                      color: string;
                      stop: number;
                      id?: string | null;
                    }[]
                  | null;
              };
              effect?: ('none' | 'appear' | 'zoom' | 'slide') | null;
              accentColor?: string | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoBlock".
 */
export interface BentoBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  items?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        background: {
          type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
          inverted?: boolean | null;
          dark?: boolean | null;
          backgroundImage?: (string | null) | Media;
          color?: string | null;
          colorStops?:
            | {
                color: string;
                stop: number;
                id?: string | null;
              }[]
            | null;
        };
        accentColor?: string | null;
        rowSpan?: number | null;
        colSpan?: number | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bento';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    name: string;
    role: string;
    quote: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    avatar?: (string | null) | Media;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null);
      url?: string | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  faqs: {
    question?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  members: {
    name?: string | null;
    role?: string | null;
    bio?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    photo?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPostsBlock".
 */
export interface RelatedPostsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  relatedPosts?: (string | Post)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  form: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  event?: ('submission' | 'registration') | null;
  mailchimpList?: string | null;
  mailchimpTags?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandBlock".
 */
export interface BrandBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  logos?:
    | {
        svgLogo: string | Media;
        pngLogo: string | Media;
        variant?: ('light' | 'dark') | null;
        id?: string | null;
      }[]
    | null;
  colors?:
    | {
        name: string;
        color: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JobsBlock".
 */
export interface JobsBlock {
  title?: string | null;
  heading: 'h2' | 'h3' | 'h4';
  subtitle?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleSize?: ('xs' | 'sm' | 'default' | 'lg') | null;
  centered?: boolean | null;
  forceFullWidth?: boolean | null;
  background: {
    type: 'none' | 'color' | 'image' | 'verticalGradient' | 'horizontalGradient';
    inverted?: boolean | null;
    dark?: boolean | null;
    backgroundImage?: (string | null) | Media;
    color?: string | null;
    colorStops?:
      | {
          color: string;
          stop: number;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'jobs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  name: string;
  location?: string | null;
  salary?: string | null;
  type?: ('full-time' | 'part-time' | 'contract' | 'freelance' | 'internship') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?: (string | null) | Media;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          sublinks?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  icon?: (string | null) | Media;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  groups?:
    | {
        title: string;
        groupItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: string;
  socials?:
    | {
        social:
          | 'facebook'
          | 'twitter'
          | 'instagram'
          | 'linkedin'
          | 'github'
          | 'youtube'
          | 'pinterest'
          | 'tiktok'
          | 'snapchat'
          | 'telegram'
          | 'signal'
          | 'discord'
          | 'twitch'
          | 'reddit';
        link: string;
        id?: string | null;
      }[]
    | null;
  companyName: string;
  companyEmail: string;
  companyFoundedDate: string;
  companyAddress: {
    streetAddress: string;
    state: string;
    zip: string;
    country: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('ts' | 'tsx' | 'js' | 'json' | 'css' | 'bash' | 'csharp') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}