name: Deploy on Hosting

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: ${{ endsWith(github.ref, '/main') && 'production' || 'development' }}

    env:
      PUBLIC_DIRECTUS_URL: ${{ secrets.PUBLIC_DIRECTUS_URL }}
      PUBLIC_DIRECTUS_PROJECT: ${{ secrets.PUBLIC_DIRECTUS_PROJECT }}
      DIRECTUS_PROJECT: "etherna"
      DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      DISABLE_SOURCEMAP: "true"
      SITE_URL: ${{ secrets.SITE_URL }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          architecture: "x64"

      - name: Install dependencies
        run: yarn install --ignore-optional

      - name: Build site
        run: yarn build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

  publish_host:
    name: Publish to Host
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

      - name: Upload to Host
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: dist
          remoteDir: ${{ secrets.FTP_REMOTE_DIR }}
          options: "--delete -X cgi-bin/ -X .well-known/"
