name: Deploy on Hosting

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Deploy Gatsby Site
    environment:
      name: ${{ endsWith(github.ref, '/main') && 'production' || 'development' }}
    env:
      DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
      DIRECTUS_PROJECT: "etherna"
      DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      DISABLE_SOURCEMAP: "true"
      SITE_URL: ${{ secrets.SITE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.1.0
      - name: Build Gatsby
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'
      - run: yarn install --ignore-optional
      - run: yarn build
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "public"
          remoteDir: ${{ secrets.FTP_REMOTE_DIR }}
          options: "--delete -X cgi-bin/ -X .well-known/"
