name: Deploy on Hosting

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy Gatsby Site
    env:
      DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
      DIRECTUS_PROJECT: "etherna"
      DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
      DISABLE_SOURCEMAP: "true"
      SITE_URL: ${{ secrets.SITE_URL }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build Gatsby Site
      uses: mattiaz9/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"
        remoteDir: ${{ secrets.REMOTE_DIR }}
        options: "--delete -X cgi-bin/ -X .well-known/"
