name: Deploy on Hosting (webhook)

on:
  workflow_dispatch:
    inputs:
      passphrase:
        required: true

jobs:
  build:
    name: Deploy Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Validate with secret
      uses: mattiaz9/conditional-cancel-action@0.1
      with:
        match_1: ${{ secrets.PASSPHRASE }}
        match_2: ${{ github.event.inputs.passphrase }}
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      env:
        DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
        DIRECTUS_PROJECT: "etherna"
        DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
        DISABLE_SOURCEMAP: "true"
      with:
        gatsby-arg: build
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"
        remoteDir: ${{ secrets.REMOTE_DIR }}
